# Generated by Django 2.0.5 on 2018-09-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(default='images/recursos/None/no-img.jpg', upload_to='images/recursos/')),
                ('nomnbre', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
