# Generated by Django 2.0.5 on 2018-09-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICR_CS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='nomnbre',
            new_name='resultado',
        ),
    ]
